csv_sample1="""
              RT_M_ACCT_TYPE_TEXT         Account Type Unnamed: 2  Unnamed: 3  Unnamed: 4   Projection Unnamed: 6        Unnamed: 7 Unnamed: 8  Unnamed: 9               LT_M_ACCT_TYPE_TEXT Account Type.1 Unnamed: 12 Unnamed: 13   Unnamed: 14      Unnamed: 15 Unnamed: 16
                  Connection Name                  EC3        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                  Datasource Name SAPI.0ACCT_TYPE_TEXT        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                              NaN                  NaN        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                    Business Name       Technical Name  Data Type         NaN         NaN        Label    Columns               NaN     Filter         NaN                     Business Name Technical Name         Key   Data Type Semantic Type Text/Association    Not Null
                     Language Key                LANGU  String(1)         NaN         NaN Projection 1      LANGU               NaN        NaN         NaN                      Language Key          LANGU           X   String(1)      Language              NaN           X
Key Field for DataSource for Text                 KEY1 String(60)         NaN         NaN          NaN       KEY1               NaN        NaN         NaN Key Field for DataSource for Text           KEY1           X  String(60)           NaN            TXTLG           X
                 Long description                TXTLG String(60)         NaN         NaN          NaN      TXTLG               NaN        NaN         NaN                  Long description          TXTLG         NaN  String(60)          Text              NaN         NaN
                              NaN                  NaN        NaN         NaN         NaN          NaN    CC_TEXT Calculated Column        NaN         NaN                       Text Column        CC_TEXT         NaN  String(20)           NaN              NaN         NaN
                              NaN                  NaN        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                              NaN                  NaN        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                           Source                  NaN        NaN         NaN         NaN          NaN        NaN               NaN        NaN         NaN                               NaN            NaN         NaN         NaN           NaN              NaN         NaN
                              NaN                  NaN        NaN         NaN         NaN   Projection        NaN               NaN        NaN         NaN                           Target             NaN         NaN         NaN           NaN              NaN         NaN
 """