csv_sample2="""

                           Source     Unnamed: 1 Unnamed: 2  Unnamed: 3  Projection  Unnamed: 5 Unnamed: 6         Unnamed: 7          Unnamed: 8  Unnamed: 9    Unnamed: 10                            Target    Unnamed: 12 Unnamed: 13   Unnamed: 14      Unnamed: 15 Unnamed: 16
                              NaN            NaN        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                    Business Name       Job Text        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN  Busniess Name                          Job Text            NaN         NaN           NaN              NaN         NaN
                   Technical Name RT_M_0JOB_TEXT        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN Technical Name                    LT_M_0JOB_TEXT            NaN         NaN           NaN              NaN         NaN
                              NaN            NaN        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                  Connection Name            EC3        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                  DataSource Name SAPI.0JOB_TEXT        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                              NaN            NaN        NaN         NaN         NaN         NaN        NaN                NaN                 NaN         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                   Busniness Name Technical Name  Data Type         NaN       Label     Columns  Data Type                NaN                 NaN         NaN            Key                     Business Name Technical Name   Data Type Semantic Type Text/Association    Not Null
                     Language Key          LANGU  String(1)         NaN Projetion 1       LANGU  String(1)                NaN                 NaN         NaN              X                      Language Key          LANGU   String(1)      Language              NaN           X
Key Field for DataSource for Text           KEY1 String(60)         NaN         NaN        KEY1 String(60)                NaN                 NaN         NaN              X Key Field for DataSource for Text           KEY1  String(60)           NaN            TXTMD           X
                    Valid-to date         DATETO  String(8)         NaN         NaN      DATETO  String(8)                NaN                 NaN         NaN              X                     Valid-to date         DATETO        Date           NaN              NaN           X
                  Valid-From Date       DATEFROM  String(8)         NaN         NaN    DATEFROM  String(8)                NaN                 NaN         NaN            NaN                   Valid-From Date       DATEFROM        Date           NaN              NaN         NaN
                Short description          TXTSH String(20)         NaN         NaN       TXTSH String(20)                NaN                 NaN         NaN            NaN                 Short description          TXTSH  String(20)           NaN              NaN         NaN
               Medium description          TXTMD String(40)         NaN         NaN       TXTMD String(40)                NaN                 NaN         NaN            NaN                Medium description          TXTMD  String(40)          Text              NaN         NaN
                              NaN            NaN        NaN         NaN         NaN   CC_DATETO       Date Calculated Columns   To_Date("DATETO")         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
                              NaN            NaN        NaN         NaN         NaN CC_DATEFROM       Date Calculated Columns To_Date("DATEFROM")         NaN            NaN                               NaN            NaN         NaN           NaN              NaN         NaN
"""