csv_sample3="""
                 Source             Unnamed: 1 Unnamed: 2  Unnamed: 3   Projection              Unnamed: 5 Unnamed: 6         Unnamed: 7          Unnamed: 8  Unnamed: 9         Target             Unnamed: 11    Unnamed: 12 Unnamed: 13 Unnamed: 14
                    NaN                    NaN        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN            NaN                     NaN            NaN         NaN         NaN
          Business Name Cost Element Attribute        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN  Busniess Name  Cost Element Attribute            NaN         NaN         NaN
         Technical Name RT_M_0COSTELEMENT_ATTR        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN Technical Name  LT_M_0COSTELEMENT_ATTR            NaN         NaN         NaN
                    NaN                    NaN        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN            NaN                     NaN            NaN         NaN         NaN
        Connection Name                    EC3        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN            NaN                     NaN            NaN         NaN         NaN
        DataSource Name   SAPI.0COSTELMNT_ATTR        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN            NaN                     NaN            NaN         NaN         NaN
                    NaN                    NaN        NaN         NaN          NaN                     NaN        NaN                NaN                 NaN         NaN            NaN                     NaN            NaN         NaN         NaN
         Busniness Name         Technical Name  Data Type         NaN        Label                 Columns   DataType                NaN                 NaN         NaN            Key           Business Name Technical Name   Data Type    Not Null
       Controlling Area                  KOKRS  String(4)         NaN Projection 1        Controlling Area  String(4)                NaN                 NaN         NaN              X        Controlling Area          KOKRS   String(4)           X
           Cost Element                  KSTAR String(10)         NaN          NaN            Cost Element String(10)                NaN                 NaN         NaN              X            Cost Element          KSTAR  String(10)           X
          Valid To Date                 DATETO  String(8)         NaN          NaN           Valid To Date  String(8)                NaN                 NaN         NaN              X           Valid To Date         DATETO        Date           X
        Valid-From Date               DATEFROM  String(8)         NaN          NaN         Valid-From Date  String(8)                NaN                 NaN         NaN            NaN         Valid-From Date       DATEFROM        Date         NaN
  Cost element category                  KATYP  String(2)         NaN          NaN   Cost element category  String(2)                NaN                 NaN         NaN            NaN   Cost element category          KATYP   String(2)         NaN
Cost element attributes                  EIGEN  String(8)         NaN          NaN Cost element attributes  String(8)                NaN                 NaN         NaN            NaN Cost element attributes          EIGEN   String(8)         NaN
    Unit of Measurement                  MSEHI  String(5)         NaN          NaN     Unit of Measurement  String(5)                NaN                 NaN         NaN            NaN     Unit of Measurement          MSEHI   String(5)         NaN
                    NaN                    NaN        NaN         NaN          NaN             CC_DATEFROM       Date  Calculated Column TO_DATE("DATEFROM")         NaN            NaN                     NaN            NaN         NaN         NaN
                    NaN                    NaN        NaN         NaN          NaN               CC_DATETO       Date Calculated Column    TO_DATE("DATETO")         NaN            NaN                     NaN            NaN         NaN         NaN

"""